# Generated by Django 4.1.2 on 2022-10-07 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_teathersstudents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeathersStudents',
        ),
    ]
